name: XCS234
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - notebook=7.3.2
  - tk=8.6.14
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - tensorboard=2.17.0
  - pyyaml=6.0.2
  - pip=25.0
  - pip:
    - setuptools==76.0.0
    - cmake==3.31.6; sys_platform != "win32"
    - wget==3.2; sys_platform != "win32"
    - matplotlib==3.10.1
    - tqdm==4.67.1
    - imageio==2.37.0
    - numpy==2.2.3
    - pandas==2.2.3
    - scipy==1.15.2
    - bottleneck==1.4.2
    - ale-py==0.10.2
    - pygame==2.6.1
    - pyglet==2.1.3
    - autorom[accept-rom-license]==0.6.1
    - dm-control==1.0.28
    - gymnasium[mujoco]==1.1.1
    # Issue with the command below. 
    # - stable-baselines3[extra]
    # Use the GitHub as source for the Winter 2025 Cohort with version 2.6.0a2
    - "stable_baselines3[extra] @ git+https://github.com/DLR-RM/stable-baselines3"
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.6.0; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.6.0+cpu; sys_platform == "linux" or sys_platform == "win32"
